#!/usr/bin/env bash
# Installs nginx on server, nginx listens on port 80, return a page saying Hello World!
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
